steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/mlops-14-project-deploy-fast/repositorio-mlops-inofuente/imagen-v6-mlops-inofuente:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/mlops-14-project-deploy-fast/repositorio-mlops-inofuente/imagen-v6-mlops-inofuente:latest']
