apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: servicio-proyecto-vision-yolo
spec:
  template:
    spec:
      containers:
        - image: 'northamerica-south1-docker.pkg.dev/mlops-14-project-deploy-fast/repositorio-mlops-jair-ramos/imagen-v6-mlops-jair-ramos:latest'
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: 1Gi
